name: WAStickers
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  flutter_bloc: ^7.0.0
  device_apps: ^2.2.0
  cupertino_icons: ^1.0.5
  flutter_whatsapp_stickers: 1.0.1+5
  url_launcher: 6.1.12
  flutter_screenutil: 5.8.4
  palette_generator: 0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/
    - sticker_packs/1/
    - sticker_packs/2/
    - sticker_packs/3/
    - sticker_packs/4/
    - sticker_packs/5/
    - sticker_packs/6/
    - sticker_packs/7/
    - sticker_packs/8/
    - sticker_packs/9/
    - sticker_packs/10/
    - sticker_packs/11/
    - sticker_packs/12/
    - sticker_packs/13/
    - sticker_packs/14/
    - sticker_packs/15/
    - sticker_packs/16/
    - sticker_packs/17/
    - sticker_packs/18/
    - sticker_packs/19/
    - sticker_packs/20/
    - sticker_packs/21/
    - sticker_packs/22/
    - sticker_packs/23/
    - sticker_packs/24/
    - sticker_packs/sticker_packs.json
    - sticker_packs/all_packs.json
    - sticker_packs/featured_pack.json

 
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/AvenirLTStd-Roman.otf
